### ISSUE TITLE
Known Emscripten issue to report upstream

### ISSUE THREAD

**Issue by tiran** [ethanhs/python-wasm#43]
A ticket to collect issues and bugs with Emscripten. We want to report them upstream eventually.

- [x] Emscripten defines ``IPPROTO_SCTP``, but ``socket(AF_INET, SOCK_STREAM, IPPROTO_SCTP)`` causes an abort, https://github.com/emscripten-core/emscripten/pull/16479
- [x] ``clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &timeout_abs, NULL)`` does not work as expected, causes ``time.sleep`` to hang forever. ``nanosleep(&timeout_ts, NULL)`` works. https://github.com/emscripten-core/emscripten/issues/16453
- [X] ``freeaddrinfo`` crash https://github.com/emscripten-core/emscripten/issues/16081
- [X] ``strftime`` mishandles quoted percent, https://github.com/emscripten-core/emscripten/issues/16155
- [x] week number of ``strftime("%U")`` and ``%W`` wrong https://github.com/emscripten-core/emscripten/issues/16156
- [ ] ``mkfifo()`` and ``mknod()`` create regular file https://github.com/emscripten-core/emscripten/issues/16158
- [x] ``opendir`` / ``open(O_DIRECTORY)`` leaks file directory https://github.com/emscripten-core/emscripten/issues/16452
- [X] msync() on anonymous mapping fails, https://github.com/emscripten-core/emscripten/issues/16350
- [ ] ``fstat`` does not work on pipes, https://github.com/emscripten-core/emscripten/issues/16414 and https://github.com/python/cpython/pull/31770
- [ ] ``fstat`` does not work on unlinked file
- [x] Blocking socket ``accept()`` fails with ``TypeError: Cannot read property 'stream' of undefined``, https://github.com/emscripten-core/emscripten/issues/16047
- [x] utimensat sets wrong atime and mtime, https://github.com/emscripten-core/emscripten/issues/16458
- [ ] ``umask`` is stubbed
- [ ] ``select`` does not support non-NULL ``exceptfds``, crashes with assertion error. CPython workaround https://github.com/python/cpython/pull/31865
- [X] strftime ``%V`` issue, https://github.com/emscripten-core/emscripten/pull/16494

**Comment by emmatyping** [comment]
I'm actually surprised a nanosecond timer works at all considering the spectre mitigations

**Comment by tiran** [comment]
* ``freeaddrinfo`` crash https://github.com/emscripten-core/emscripten/issues/16081

**Comment by tiran** [comment]
* ``strftime`` mishandles quoted percent, https://github.com/emscripten-core/emscripten/issues/16155

**Comment by brettcannon** [comment]
Did the two initial issues get reported upstream? Based on how they already fixed the last two issues Christian reported it seems the Emscripten folks are quick to fix things.

**Comment by tiran** [comment]
> Did the two initial issues get reported upstream? Based on how they already fixed the last two issues Christian reported it seems the Emscripten folks are quick to fix things.

No, I haven't had time to create simple reproducers in C for the two initial bugs.
